/** Single-word glosses from published Rohingyalish dictionaries. */
export const LEXICON: { en: string; rhg: string; aliases?: string[] }[] = [
  { en: "water", rhg: "faní" },
  { en: "food", rhg: "hána", aliases: ["meal"] },
  { en: "rice", rhg: "bát" },
  { en: "house", rhg: "gór", aliases: ["home", "housing"] },
  { en: "family", rhg: "górguccí" },
  { en: "child", rhg: "fua", aliases: ["kid", "son"] },
  { en: "children", rhg: "fuain", aliases: ["kids"] },
  { en: "daughter", rhg: "zíi" },
  { en: "mother", rhg: "maa", aliases: ["mom"] },
  { en: "father", rhg: "abba", aliases: ["dad"] },
  { en: "brother", rhg: "bái" },
  { en: "sister", rhg: "bóin" },
  { en: "husband", rhg: "beça" },
  { en: "wife", rhg: "bou" },
  { en: "doctor", rhg: "daktor" },
  { en: "hospital", rhg: "hóspital" },
  { en: "medicine", rhg: "dabai", aliases: ["medication", "pills"] },
  { en: "pain", rhg: "bic" },
  { en: "fever", rhg: "zor" },
  { en: "sick", rhg: "ocúk", aliases: ["ill"] },
  { en: "help", rhg: "modot" },
  { en: "interpreter", rhg: "hotá báñgidoya", aliases: ["translator"] },
  { en: "school", rhg: "eskul" },
  { en: "work", rhg: "ham", aliases: ["job"] },
  { en: "money", rhg: "thiañ" },
  { en: "rent", rhg: "keriya" },
  { en: "paper", rhg: "habos" },
  { en: "form", rhg: "fórom" },
  { en: "card", rhg: "kaádh", aliases: ["id"] },
  { en: "phone", rhg: "fún" },
  { en: "address", rhg: "thíkana" },
  { en: "bus", rhg: "baás" },
  { en: "car", rhg: "garí" },
  { en: "appointment", rhg: "thaimluwa" },
  { en: "passport", rhg: "paásputh" },
  { en: "notice", rhg: "notís" },
  { en: "proof", rhg: "sóbut" },
  { en: "bring", rhg: "anó" },
  { en: "today", rhg: "aijja" },
  { en: "tomorrow", rhg: "hailla" },
  { en: "please", rhg: "meérbanigorí" },
  { en: "slowly", rhg: "asté" },
  { en: "again", rhg: "abbar" },
  { en: "english", rhg: "Ingilíc" },
  { en: "language", rhg: "zuban" },
  { en: "name", rhg: "nam" },
  { en: "health", rhg: "sehét" },
  { en: "emergency", rhg: "emarjensi" },
  { en: "toilet", rhg: "thaththi", aliases: ["washroom", "bathroom", "restroom"] },
  { en: "here", rhg: "eçé" },
  { en: "where", rhg: "hoçé" },
  { en: "yes", rhg: "ói" },
  { en: "no", rhg: "noó" },
  { en: "thank you", rhg: "tuáñre cúkuria", aliases: ["thanks"] },
  { en: "book", rhg: "kitab" },
  { en: "come", rhg: "aiyó" },
  { en: "wait", rhg: "tíyo" },
  { en: "free", rhg: "maana" },
  { en: "happy", rhg: "kúci" },
  { en: "hungry", rhg: "buk" },
  { en: "thirsty", rhg: "tirác" },
  { en: "cold", rhg: "thándhah" },
  { en: "good", rhg: "gom", aliases: ["well"] },
  { en: "one", rhg: "ek" },
  { en: "two", rhg: "dui" },
  { en: "three", rhg: "tin" },
  { en: "four", rhg: "sair" },
  { en: "five", rhg: "fañs" },
  { en: "six", rhg: "só" },
  { en: "seven", rhg: "háñt" },
  { en: "eight", rhg: "añctho" },
  { en: "nine", rhg: "no" },
  { en: "ten", rhg: "doc" },
];
