import type { Phrase } from "./types";

/**
 * Settlement phrasebook for Welcome Centre staff and Rohingya newcomers.
 *
 * `phrasebook` rows are published Rohingyalish sentences from NGO/learner
 * materials (RohingyaLanguage.org phrasebook, NGO phrases, beginner lessons).
 * `composed` rows follow documented grammar (Añáttu X lage, X hoçé?) using
 * dictionary headwords. Always show the source badge in the UI.
 */
export const PHRASES: Phrase[] = [
  // Greetings
  {
    id: "hi",
    en: "Hello / Peace be upon you",
    rhg: "Assalamu alaikum",
    category: "greetings",
    aliases: ["hello", "hi", "salaam", "salam", "peace be upon you", "greeting"],
    source: "phrasebook",
    notes: "Standard Islamic greeting used across Rohingya communities.",
  },
  {
    id: "hi-reply",
    en: "Peace be upon you too",
    rhg: "Wa alaikum assalam",
    category: "greetings",
    aliases: ["reply", "hello back", "walaikum"],
    source: "phrasebook",
  },
  {
    id: "how-are-you",
    en: "Are you well? How are you?",
    rhg: "Bála aso ne?",
    category: "greetings",
    aliases: ["how are you", "are you well", "how do you do"],
    source: "phrasebook",
    notes: "Formal. Informal: Gom aso ne?",
  },
  {
    id: "how-are-you-informal",
    en: "Are you well? (informal)",
    rhg: "Gom aso ne?",
    category: "greetings",
    aliases: ["how are you informal"],
    source: "phrasebook",
  },
  {
    id: "i-am-fine",
    en: "Yes, I am fine",
    rhg: "Ói, aññí bála asi",
    category: "greetings",
    aliases: ["i am fine", "i am well", "i'm good", "i am good"],
    source: "phrasebook",
  },
  {
    id: "have-you-eaten",
    en: "Have you eaten? (friendly greeting)",
    rhg: "Bát haiyó ne?",
    category: "greetings",
    aliases: ["have you eaten", "have you eaten rice", "how are you really"],
    source: "phrasebook",
    notes: "A warm everyday greeting. Answer Háiyi if you have eaten / are well.",
  },
  {
    id: "i-have-eaten",
    en: "I have eaten",
    rhg: "Háiyi",
    category: "greetings",
    aliases: ["i ate", "i've eaten"],
    source: "phrasebook",
  },
  {
    id: "your-name",
    en: "What is your name?",
    rhg: "Tuáñr nam ki?",
    category: "greetings",
    aliases: ["what's your name", "name"],
    source: "phrasebook",
  },
  {
    id: "my-name",
    en: "My name is…",
    rhg: "Añár nam…",
    category: "greetings",
    aliases: ["my name is", "i am called"],
    source: "phrasebook",
  },
  {
    id: "thank-you",
    en: "Thank you",
    rhg: "Tuáñre cúkuria",
    category: "greetings",
    aliases: ["thanks", "thank you very much", "shukria"],
    source: "phrasebook",
  },
  {
    id: "yes",
    en: "Yes",
    rhg: "Ói",
    category: "greetings",
    aliases: ["yeah", "yep"],
    source: "phrasebook",
  },
  {
    id: "no",
    en: "No",
    rhg: "Noó",
    category: "greetings",
    aliases: ["nope"],
    source: "phrasebook",
  },
  {
    id: "see-you",
    en: "See you again",
    rhg: "Abbar deha oibó!",
    category: "greetings",
    aliases: ["goodbye", "bye", "see you later", "see you"],
    source: "phrasebook",
  },
  {
    id: "understand",
    en: "Do you understand?",
    rhg: "Tuñí buzó ne?",
    category: "greetings",
    aliases: ["do you understand", "understand"],
    source: "phrasebook",
  },
  {
    id: "dont-understand",
    en: "I don't understand",
    rhg: "Aññí no buzí",
    category: "greetings",
    aliases: ["i do not understand", "i don't get it", "what"],
    source: "phrasebook",
    notes: "Negation comes before the verb.",
  },
  {
    id: "where-from",
    en: "Where are you from?",
    rhg: "Tuñí hon zagar?",
    category: "greetings",
    aliases: ["where are you from", "origin"],
    source: "phrasebook",
  },
  {
    id: "where-live",
    en: "Where do you live?",
    rhg: "Tuñí hoçé tako?",
    category: "housing",
    aliases: ["where do you live", "where is your home"],
    source: "phrasebook",
  },
  {
    id: "we-live-here",
    en: "We live here",
    rhg: "Añára eçé taki",
    category: "housing",
    aliases: ["we live here", "i live here"],
    source: "phrasebook",
  },

  // Welcome Centre
  {
    id: "need-help",
    en: "Do you need help?",
    rhg: "Tuáñttu modot lage ne?",
    category: "centre",
    aliases: ["do you need help", "need help", "can i help"],
    source: "phrasebook",
  },
  {
    id: "we-will-help",
    en: "We will help you",
    rhg: "Añára tuáñre modot goríyum",
    category: "centre",
    aliases: ["we will help", "we can help", "we are here to help"],
    source: "phrasebook",
  },
  {
    id: "dont-be-afraid",
    en: "Do not be afraid",
    rhg: "No dhoraiyó",
    category: "centre",
    aliases: ["don't be afraid", "don't worry", "you are safe"],
    source: "phrasebook",
  },
  {
    id: "wait-here",
    en: "Please wait here",
    rhg: "Eçé tíyo",
    category: "centre",
    aliases: ["wait here", "please wait", "sit here", "wait"],
    source: "phrasebook",
  },
  {
    id: "come-with-me",
    en: "Come with me",
    rhg: "Añár loi aiyó",
    category: "centre",
    aliases: ["follow me", "come this way", "this way"],
    source: "phrasebook",
  },
  {
    id: "welcome",
    en: "Welcome",
    rhg: "Aiyó aiyó",
    category: "centre",
    aliases: ["welcome", "you are welcome"],
    source: "composed",
    notes: "Dictionary greeting. Formal: tuáñre baráiloir.",
  },
  {
    id: "welcome-centre",
    en: "Welcome to the Welcome Centre",
    rhg: "Welcome Centre ot tuáñre baráiloir",
    category: "centre",
    aliases: ["welcome centre", "welcome to the centre"],
    source: "composed",
    notes: "Proper noun kept in English; baráiloir is a documented welcome verb.",
  },
  {
    id: "need-interpreter",
    en: "I need an interpreter",
    rhg: "Añáttu hotá báñgidoya lage",
    category: "centre",
    aliases: [
      "i need an interpreter",
      "i need a translator",
      "interpreter please",
      "translator",
    ],
    source: "composed",
    notes: "Uses the Añáttu X lage pattern with the dictionary word for interpreter.",
  },
  {
    id: "this-is-free",
    en: "This is free",
    rhg: "Yián maana",
    category: "centre",
    aliases: ["this is free", "no cost", "no charge", "free of charge"],
    source: "composed",
  },
  {
    id: "speak-slowly",
    en: "Please speak slowly",
    rhg: "Meérbanigorí asté hotáhoó",
    category: "centre",
    aliases: ["speak slowly", "slow down", "please speak slower"],
    source: "composed",
  },
  {
    id: "say-again",
    en: "Please say that again",
    rhg: "Meérbanigorí abbar hotáhoó",
    category: "centre",
    aliases: ["say again", "repeat", "one more time", "pardon"],
    source: "composed",
  },
  {
    id: "no-english",
    en: "I don't speak English",
    rhg: "Aññí Ingilíc no hotáhoó",
    category: "centre",
    aliases: ["i don't speak english", "no english", "i cannot speak english"],
    source: "composed",
  },
  {
    id: "appointment-today",
    en: "My appointment is today",
    rhg: "Añár thaimluwa aijja",
    category: "centre",
    aliases: ["appointment today", "i have an appointment today"],
    source: "composed",
  },
  {
    id: "appointment-tomorrow",
    en: "My appointment is tomorrow",
    rhg: "Añár thaimluwa hailla",
    category: "centre",
    aliases: ["appointment tomorrow", "i have an appointment tomorrow"],
    source: "composed",
  },
  {
    id: "have-appointment",
    en: "Do you have an appointment?",
    rhg: "Tuáñttu thaimluwa asé ne?",
    category: "centre",
    aliases: ["do you have an appointment", "appointment"],
    source: "composed",
  },
  {
    id: "toilet-here",
    en: "The washroom is here",
    rhg: "Thaththi eçé",
    category: "centre",
    aliases: ["bathroom is here", "toilet is here", "washroom"],
    source: "composed",
  },
  {
    id: "where-toilet",
    en: "Where is the toilet?",
    rhg: "Thaththi hoçé?",
    category: "centre",
    aliases: ["where is the bathroom", "where is the washroom", "restroom"],
    source: "composed",
  },
  {
    id: "please-come",
    en: "Please come here",
    rhg: "Meérbanigorí eçé aiyó",
    category: "centre",
    aliases: ["come here", "please come"],
    source: "composed",
  },

  // Health
  {
    id: "feeling-well",
    en: "Are you feeling well?",
    rhg: "Tuáñttu gom lager ne?",
    category: "health",
    aliases: ["are you feeling well", "how do you feel"],
    source: "phrasebook",
  },
  {
    id: "i-am-well",
    en: "I am well",
    rhg: "Añáttu gom lager",
    category: "health",
    aliases: ["i feel well", "i feel good"],
    source: "phrasebook",
  },
  {
    id: "i-am-sick",
    en: "I am sick",
    rhg: "Añáttu gaat ocúk",
    category: "health",
    aliases: ["i am ill", "i feel sick", "i'm not well", "i am not well"],
    source: "phrasebook",
  },
  {
    id: "fever",
    en: "Do you have a fever?",
    rhg: "Tuáñr gaat zor asé ne?",
    category: "health",
    aliases: ["fever", "temperature", "do you have a fever"],
    source: "phrasebook",
  },
  {
    id: "where-hurt",
    en: "Where does it hurt?",
    rhg: "Hoçé bic goré?",
    category: "health",
    aliases: ["where does it hurt", "pain where", "what hurts"],
    source: "phrasebook",
  },
  {
    id: "take-medicine",
    en: "Take this medicine",
    rhg: "Yián dabai há",
    category: "health",
    aliases: ["take this medicine", "take this medication"],
    source: "phrasebook",
  },
  {
    id: "drink-water",
    en: "Drink water",
    rhg: "Faní fiyo",
    category: "health",
    aliases: ["drink water", "have some water"],
    source: "phrasebook",
  },
  {
    id: "need-doctor",
    en: "I need a doctor",
    rhg: "Añáttu daktor lage",
    category: "health",
    aliases: ["i need a doctor", "doctor please", "see a doctor"],
    source: "phrasebook",
  },
  {
    id: "doctor",
    en: "Doctor",
    rhg: "daktor",
    category: "health",
    aliases: ["physician"],
    source: "phrasebook",
  },
  {
    id: "medicine",
    en: "Medicine",
    rhg: "dabai",
    category: "health",
    aliases: ["medication", "pills", "drugs"],
    source: "phrasebook",
  },
  {
    id: "hospital",
    en: "Hospital",
    rhg: "hóspital",
    category: "health",
    aliases: ["clinic", "hospital"],
    source: "phrasebook",
  },
  {
    id: "where-hospital",
    en: "Where is the hospital?",
    rhg: "Hóspital hoçé?",
    category: "health",
    aliases: ["where is the hospital", "where is the clinic"],
    source: "composed",
  },
  {
    id: "need-health-help",
    en: "I need help with health care",
    rhg: "Añáttu sehétor modot lage",
    category: "health",
    aliases: ["health care", "healthcare", "medical help", "i need health help"],
    source: "composed",
  },
  {
    id: "happy",
    en: "I feel happy",
    rhg: "Añáttu kúci lager",
    category: "health",
    aliases: ["i am happy", "i feel happy"],
    source: "phrasebook",
  },
  {
    id: "not-hungry",
    en: "I am not hungry",
    rhg: "Añáttu buk no lager",
    category: "food",
    aliases: ["not hungry"],
    source: "phrasebook",
  },

  // Housing
  {
    id: "need-house",
    en: "I need a house",
    rhg: "Añáttu gór lage",
    category: "housing",
    aliases: ["i need a house", "i need housing", "i need a home", "apartment"],
    source: "composed",
  },
  {
    id: "need-housing-help",
    en: "I need help with housing",
    rhg: "Añáttu góror modot lage",
    category: "housing",
    aliases: ["housing help", "help with housing", "find housing"],
    source: "composed",
  },
  {
    id: "rent",
    en: "Rent",
    rhg: "keriya",
    category: "housing",
    aliases: ["rent", "rental"],
    source: "composed",
  },
  {
    id: "my-address",
    en: "This is my address",
    rhg: "Yián añár thíkana",
    category: "housing",
    aliases: ["my address", "this is my address", "address"],
    source: "composed",
  },
  {
    id: "where-bus",
    en: "Where is the bus?",
    rhg: "Baás hoçé?",
    category: "housing",
    aliases: ["where is the bus", "bus stop", "transit"],
    source: "composed",
  },

  // Family
  {
    id: "where-family",
    en: "Where is your family?",
    rhg: "Tuáñr górguccí hoçé?",
    category: "family",
    aliases: ["where is your family", "family where"],
    source: "phrasebook",
  },
  {
    id: "this-is-daughter",
    en: "This is our daughter",
    rhg: "Ibá añárar zíi",
    category: "family",
    aliases: ["daughter", "this is our daughter"],
    source: "phrasebook",
  },
  {
    id: "this-is-son",
    en: "This is our son",
    rhg: "Ibá añárar fua",
    category: "family",
    aliases: ["son", "this is our son", "this is our child"],
    source: "phrasebook",
  },
  {
    id: "three-sisters",
    en: "I have three sisters",
    rhg: "Añáttu tin bóin asé",
    category: "family",
    aliases: ["sisters"],
    source: "phrasebook",
  },
  {
    id: "mother",
    en: "Mother",
    rhg: "maa",
    category: "family",
    aliases: ["mom", "mum"],
    source: "phrasebook",
  },
  {
    id: "father",
    en: "Father",
    rhg: "abba",
    category: "family",
    aliases: ["dad"],
    source: "phrasebook",
  },
  {
    id: "husband",
    en: "Husband",
    rhg: "beça",
    category: "family",
    aliases: ["husband", "spouse male"],
    source: "phrasebook",
  },
  {
    id: "wife",
    en: "Wife",
    rhg: "bou",
    category: "family",
    aliases: ["wife", "spouse female"],
    source: "phrasebook",
  },
  {
    id: "children",
    en: "Children",
    rhg: "fuain",
    category: "family",
    aliases: ["kids", "children"],
    source: "phrasebook",
  },
  {
    id: "i-have-children",
    en: "I have children",
    rhg: "Añáttu fuain asé",
    category: "family",
    aliases: ["i have kids", "i have children"],
    source: "composed",
  },
  {
    id: "this-is-family",
    en: "This is my family",
    rhg: "Ibá añár górguccí",
    category: "family",
    aliases: ["this is my family", "my family"],
    source: "composed",
  },

  // School
  {
    id: "school",
    en: "School",
    rhg: "eskul",
    category: "school",
    aliases: ["school"],
    source: "composed",
  },
  {
    id: "where-school",
    en: "Where is the school?",
    rhg: "Eskul hoçé?",
    category: "school",
    aliases: ["where is the school"],
    source: "composed",
  },
  {
    id: "need-school-help",
    en: "I need help with school",
    rhg: "Añáttu eskulor modot lage",
    category: "school",
    aliases: ["school help", "help with school", "enrol", "enroll", "registration school"],
    source: "composed",
  },
  {
    id: "we-are-reading",
    en: "We are reading",
    rhg: "Añára forír",
    category: "school",
    aliases: ["reading", "we are reading"],
    source: "phrasebook",
  },
  {
    id: "i-am-writing",
    en: "I am writing",
    rhg: "Aññí lekír",
    category: "school",
    aliases: ["writing", "i am writing"],
    source: "phrasebook",
  },

  // Food
  {
    id: "water",
    en: "Water",
    rhg: "faní",
    category: "food",
    aliases: ["water"],
    source: "phrasebook",
  },
  {
    id: "food-rice",
    en: "Rice / food",
    rhg: "bát",
    category: "food",
    aliases: ["rice", "food"],
    source: "phrasebook",
  },
  {
    id: "food",
    en: "Food",
    rhg: "hána",
    category: "food",
    aliases: ["meal", "food"],
    source: "composed",
  },
  {
    id: "hungry",
    en: "Are you hungry?",
    rhg: "Tuáñttu buk lager ne?",
    category: "food",
    aliases: ["are you hungry", "hungry"],
    source: "phrasebook",
  },
  {
    id: "i-am-hungry",
    en: "I am hungry",
    rhg: "Añáttu buk lager",
    category: "food",
    aliases: ["i am hungry", "i feel hungry"],
    source: "phrasebook",
  },
  {
    id: "thirsty",
    en: "Are you thirsty?",
    rhg: "Tuáñttu fanír tirác lager ne?",
    category: "food",
    aliases: ["are you thirsty", "thirsty"],
    source: "phrasebook",
  },
  {
    id: "i-am-thirsty",
    en: "I am thirsty",
    rhg: "Añáttu fanír tirác lager",
    category: "food",
    aliases: ["i am thirsty", "i feel thirsty"],
    source: "phrasebook",
  },
  {
    id: "need-food",
    en: "I need food",
    rhg: "Añáttu hána lage",
    category: "food",
    aliases: ["i need food", "food bank", "i need a meal"],
    source: "composed",
  },
  {
    id: "need-water",
    en: "I need water",
    rhg: "Añáttu faní lage",
    category: "food",
    aliases: ["i need water"],
    source: "composed",
  },
  {
    id: "toilet",
    en: "Toilet",
    rhg: "thaththi / fahéna hána",
    category: "food",
    aliases: ["toilet", "bathroom", "washroom", "restroom", "wc"],
    source: "phrasebook",
  },

  // Documents
  {
    id: "id-card",
    en: "ID / registration card",
    rhg: "kaádh",
    category: "documents",
    aliases: ["id", "card", "identification", "health card", "id card"],
    source: "phrasebook",
  },
  {
    id: "date-of-birth",
    en: "Date of birth",
    rhg: "zonom tarík",
    category: "documents",
    aliases: ["date of birth", "birthday", "dob", "birth date"],
    source: "phrasebook",
  },
  {
    id: "how-many",
    en: "How many?",
    rhg: "Howá?",
    category: "documents",
    aliases: ["how many", "how much"],
    source: "phrasebook",
  },
  {
    id: "male-female",
    en: "Male / female",
    rhg: "morot / maiya",
    category: "documents",
    aliases: ["male", "female", "gender", "sex"],
    source: "phrasebook",
  },
  {
    id: "this-form",
    en: "Please fill out this form",
    rhg: "Meérbanigorí yián fórom lekó",
    category: "documents",
    aliases: ["fill out this form", "this form", "form", "paperwork"],
    source: "composed",
  },
  {
    id: "my-phone",
    en: "This is my phone number",
    rhg: "Yián añár fún",
    category: "documents",
    aliases: ["my phone", "phone number", "my number"],
    source: "composed",
  },

  // Work
  {
    id: "need-job",
    en: "I need a job",
    rhg: "Añáttu ham lage",
    category: "work",
    aliases: ["i need a job", "i need work", "employment", "looking for work"],
    source: "composed",
  },
  {
    id: "need-money",
    en: "I need money",
    rhg: "Añáttu thiañ lage",
    category: "work",
    aliases: ["i need money", "money", "financial help"],
    source: "composed",
  },
  {
    id: "what-doing",
    en: "What are you doing?",
    rhg: "Tuñí ki goró?",
    category: "work",
    aliases: ["what are you doing", "what do you do"],
    source: "phrasebook",
  },

  // Emergency
  {
    id: "are-you-safe",
    en: "Are you safe?",
    rhg: "Tuñí héfazot asó ne?",
    category: "emergency",
    aliases: ["are you safe", "safe", "safety"],
    source: "phrasebook",
  },
  {
    id: "emergency",
    en: "Emergency",
    rhg: "emarjensi",
    category: "emergency",
    aliases: ["emergency", "urgent", "911", "999"],
    source: "composed",
  },
  {
    id: "need-emergency-help",
    en: "I need emergency help",
    rhg: "Añáttu emarjensi modot lage",
    category: "emergency",
    aliases: ["emergency help", "i need emergency help", "call 911", "call ambulance"],
    source: "composed",
    notes: "For life-threatening emergencies, call local emergency services and get a qualified interpreter.",
  },
  {
    id: "appointment-notice",
    en: "Appointment notice",
    rhg: "Thaimluwa notís",
    category: "centre",
    aliases: ["appointment notice"],
    source: "composed",
    notes: "notís from the dictionary; thaimluwa is appointment.",
  },
  {
    id: "your-appointment-is",
    en: "Your appointment is",
    rhg: "Tuáñr thaimluwa",
    category: "centre",
    aliases: [
      "your appointment is scheduled for",
      "your appointment is scheduled",
      "appointment is scheduled for",
    ],
    source: "composed",
  },
  {
    id: "please-bring",
    en: "Please bring",
    rhg: "Meérbanigorí anó",
    category: "documents",
    aliases: ["please bring:", "please bring your passport", "bring your passport"],
    source: "composed",
    notes: "anó = bring. Paásputh is passport in the pictorial dictionary.",
  },
  {
    id: "passport",
    en: "Passport",
    rhg: "paásputh",
    category: "documents",
    aliases: ["passport"],
    source: "composed",
    notes: "From the Rohingya pictorial dictionary (Paásputh).",
  },
  {
    id: "proof-of-address",
    en: "Proof of address",
    rhg: "thíkanar sóbut",
    category: "documents",
    aliases: ["proof of address", "address proof"],
    source: "composed",
    notes: "sóbut = proof, thíkana = address.",
  },
];

export const PHRASE_BY_ID = new Map(PHRASES.map((phrase) => [phrase.id, phrase]));
